### PR TITLE
virts-494

### PR DESCRIPTION
**Pull request by ArtificialErmine**
Adds the ability to list and upload payloads from the chain mode gui. Requires the "listing" functionality update (https://github.com/mitre/caldera/pull/612) for file_svc in order to work.

### CODE REVIEW

**Comment by khyberspache** [comment]
I like this.  Sorry to be nit-picky, but add a <br/> below the `armored` slider

**Comment by privateducky** [comment]
can you re-base with master? there are a number of changes that are already in master, so I'm having trouble determining which changes are specific to the update and what's already there.

**Comment by khyberspache** [comment]
@privateducky I just rebased it.  This is is all new code.

**Comment by privateducky** [comment]
closing due to age + the transition of this ticket to another squad

**Pull request closed without merging**
