### PR TITLE
Add dashboard to display summary of operations.

### PR DESCRIPTION
**Pull request by minjimwu**
Currently it can list operations and calculate the success count and rate, This request only change the html(jinja) and one js file for datatable.

### CODE REVIEW

**Comment by privateducky** [comment]
This looks good at first glance. I'll test this out later today or tomorrow.

**Comment by privateducky** [comment]
all right, tested this and the code works and your implementation is nice & clean.

I'm going to leave this PR open for a little longer however, as we've been talking internally about an operation visualization, which I think may work hand-in-hand with this dashboard you've developed. 

our goal is to create a 2nd way to visualize operations (the 1st being the timeline that is built during an operation). In this 2nd view, it'll be geared toward managers (not red-teamers) and it will include more interesting visualizations (think Neo4j). we're still working through details about what this would look like, so we'll keep this PR in our back pocket for the meantime.

**Comment by minjimwu** [comment]
Sure, I am happy that you explained it in great detail. As you said, I agree if there are more charts on the page, then it will be more powerful and professional.

**Comment by privateducky** [comment]
ok-- I'm closing this PR, as we've pushed out the "reports" tab, which is the direction we're pushing for dashboard-like options for operations. the goal is to have the "operations" tab be for red-team operators (technical) and the reporting tab to be geared toward managers, with more high-level graphs/charts/etc. 

I've pushed up the general template, idea. This is still a little rough and I'm hoping we can expand on it quickly to include lots of "goodies" post-operation.

**Pull request closed without merging**
