### PR TITLE
Virts 494 list payloads redo

### PR DESCRIPTION
**Pull request by unkempthenry**
Changes: 
* new chain_svc function to list payloads  NOTE: we may want to move this function to file_svc down the road if we think multiple things will use it 
* GUI components pulled from @ArtificialErmine's https://github.com/mitre/chain/pull/186  to display the names of available payloads as a new modal 

I plan to draft a follow up PR with the ability to upload payloads to caldera, but feel like it makes sense to split the functionality into multiple PRs.

### CODE REVIEW

**Comment by unkempthenry** [comment]
rebased off master to resolve conflicts

**Review by wbooth — APPROVED** [review]
I'd make the icon a little bomb but otherwise looks great

**Comment by privateducky** [comment]
there's nothing functionally wrong with this PR (it would only require a rebase to remove the abilities section, which we did last week). but I can't see the value-add from the GUI perspective. 

you can't create abilities from the UI, only view them (through the adversary-building modal). if we allowed you to create an ability- then it would make sense to upload a payload to go along with it... 

I think there's some value in this PR though, I'm just trying to see how it could be tweaked to do so. I don't think having a modal window for payloads can be justified-- but having the list available elsewhere could be good... a few areas this may be good:

1) in the ability modal (when building an adversary) there could be a filter to see all payload abilities
2) We could add a stockpile GUI page which allows you to add and view payloads
3) other?

**Comment by wbooth** [comment]
@privateducky this PR is just to view them, but not modify the payloads, like abilities, adversaries, and facts loaded payloads could be viewed centrally.

**Comment by privateducky** [comment]
@wbooth I see that-- but I'm struggling to see the value-add. there's nothing actionable you can do, with this being a "top-level" modal. all other modals help you make decisions or allow you to change/modify stuff. off-hand, I think this would be better suited to move into the abilities "pop-up" modal via the adversaries section.

**Comment by wbooth** [comment]
closing merged into core

**Pull request closed without merging**
